'''
generate-random-playlist - Look at the generate metadata database and generate a .m3u file 
of random songs based on rating, year, genre
'''
import errno
import argparse
import os
from pathlib import Path
import random
import csv
from datetime import datetime

def main():
    parser = argparse.ArgumentParser(description='Generate a playlist of random songs based on year, genre, rating.')
    parser.add_argument('-l','--list', help='List of all files', required=True)
    parser.add_argument('-o','--output', help='Output File', required=True)
    parser.add_argument('-p','--playlist', help='Playlist title')
    parser.add_argument("-a", "--artist", action="append", help="Artist(s) to use to create list")
    parser.add_argument("-g", "--genre", action="append", help="Genre(s) to use to create list")
    parser.add_argument("-y", "--year", action="append", help="Year(s) to use to create list")
    parser.add_argument("-r", "--rating", help="Minimum rating (0-255) to filter", default=0, type=int)
    parser.add_argument("-n", "--number", help="Number of entries to generate", default=100, type=int)
    parser.add_argument("--all", help="Require all criteria (default: any)", action="store_true", default=False)
    parser.add_argument("-v", "--verbose", help="Be verbose (default: False)", action="store_true", default=False)

    args = parser.parse_args()

    if (args is None):
        print("Could not parse command line. Terminating.")
        return

    playlist = "Generated by generate-random-playlist"
    if args.playlist is not None and len(args.playlist) > 0:
        playlist = args.playlist

    recordings = []
    with open(args.list,'rt',encoding="utf-8") as f:  
        reader = csv.reader(f) 
        for line in reader:
            recording = {
                "path":line[0],
                "artist": line[1],
                "title": line[2],
                "genre": line[3],
                "rating": int(line[4]),
                "year": line[5],
                "length": int(line[6])
            }
            if args.all:
                add = True
                if len(args.artist) > 0:
                    if recording["artist"] not in args.artist:
                        add = False
                if len(args.genre) > 0:
                    if recording["genre"] not in args.genre:
                        add = False
                if len(args.year) > 0:
                    if recording["year"] not in args.year:
                        add = False
                if args.rating > 0:
                    if recording["rating"] < args.rating:
                        add = False
                if add:
                    recordings.append(recording)
            else:
                add = False
                if args.artist is not None:
                    if len(args.artist) > 0:
                        if recording["artist"] in args.artist:
                            add = True
                if args.genre is not None:
                    if len(args.genre) > 0:
                        if recording["genre"] in args.genre:
                            add = True
                if args.year is not None:
                    if len(args.year) > 0:
                        if recording["year"] in args.year:
                            add = True
                if add:
                    recordings.append(recording)

    count = len(recordings)
    items = []
    items_added = 1
    while (items_added < args.number) and (len(recordings) > 0):
        idx = random.randrange(count)
        recording = recordings[idx]
        if args.rating > 0:
            if recording["rating"] > args.rating:
                items.append(recordings[idx])
                items_added += 1
            del recordings[idx]
        else:
            items.append(recordings[idx])
            items_added += 1
            del recordings[idx]
        count -= 1

    with open(args.output, mode="wt", encoding="utf-8") as file:
        file.write("#EXTM3U\n")
        file.write("#PLAYLIST: %s\n" % (playlist))

        for item in items:
            file.write("#EXTINF:%d, %s - %s\n" % (item["length"], item["artist"], item["title"]))
            file.write("%s\n" % (item["path"]))
if __name__ == '__main__':
    main()
